<?php

namespace tests\service;

use application\service\PlushLabrador;
use PHPUnit\Framework\TestCase;

class PlushLabradorTest extends TestCase
{
    private $objectToTest;

    public function testSound() {
        $this->assertIsNotCallable([$this->objectToTest, "sound"]);
    }

    public function testHunt() {
        $this->assertIsNotCallable([$this->objectToTest, "hunt"]);
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->objectToTest = new PlushLabrador();
    }
}