<?php

namespace tests\service;

use application\service\Pug;
use PHPUnit\Framework\TestCase;

class PugTest extends TestCase
{
    private $objectToTest;

    public function testSound() {
        $this->objectToTest->sound();
        $this->expectOutputString("Ruff!\n");
    }

    public function testHunt() {
        $this->objectToTest->hunt();
        $this->expectOutputString("O-o-oh! I don`t want to hunt! It is very difficult for me!\n");
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->objectToTest = new Pug();
    }
}