<?php

namespace tests\service;

use application\service\RubberDachshund;
use PHPUnit\Framework\TestCase;

class RubberDachshundTest extends TestCase
{
    private $objectToTest;

    public function testSound() {
        $this->objectToTest->sound();
        $this->expectOutputString("Beep!\n");
    }

    public function testHunt() {
        $this->assertIsNotCallable([$this->objectToTest, "hunt"]);
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->objectToTest = new RubberDachshund();
    }
}