<?php

namespace tests\service;

use application\service\SibaInu;
use PHPUnit\Framework\TestCase;

class SibainuTest extends TestCase
{
    private $objectToTest;

    public function testSound() {
        $this->objectToTest->sound();
        $this->expectOutputString("Woof!\n");
    }

    public function testHunt() {
        $this->objectToTest->hunt();
        $this->expectOutputString("Ye-e-es!!! We are going to hunt!\n");
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->objectToTest = new SibaInu();
    }
}